### ISSUE TITLE
`rm_between` same left right boundaries gives undesired output

### ISSUE THREAD

**Issue by trinker** [trinker/qdapRegex#13]
Determine if the following is a bug and if so how to fix:
```r
x <- 'Fresh or chilled Atlantic salmon "Salmo salar" and Danube salmon "Hucho hucho"'

rm_between(
    x, 
    left = '"', right = '"',
    extract=TRUE
)

## [[1]]
## [1] "Salmo salar"       "and Danube salmon" "Hucho hucho"  
```
When we expect:
```
## [[1]]
## [1] "\"Salmo salar\"" "\"Hucho hucho\""
```

**Comment by trinker** [comment]
I think this is because the default regex of `rm_between` is to not include the left/right bounds.  This uses the following regex `"(?<=\").*?(?=\")"`.  This use of lookaheads cause the left/right bounds to not be consumed and thus allows the quotation marks to be available for: `" and Danube salmon "`.  This is (IMO) a bug that I will address but am unsure how yet.

**Comment by trinker** [comment]
@hwnd you suggested: 

```r
x <- 'Fresh or chilled Atlantic salmon "Salmo salar" and Danube salmon "Hucho hucho"'

rm_default(
    x, 
    pattern = '(?<=")[^"]*',
    extract=TRUE
)
```

But this gives:

```r
## [[1]]
## [1] "Salmo salar"         " and Danube salmon " "Hucho hucho"         ""
``

Not:

```r
## [[1]]
## [1] "Salmo salar" "Hucho hucho"
```

**Comment by mjgray09** [comment]
In the case of quotes, lookarounds should be avoided because of the "in between".

**Comment by hwndx** [comment]
One possible workaround would be:

    x <- 'Fresh or chilled Atlantic salmon "Salmo salar" and Danube salmon "Hucho hucho"'

    gsub('^"|"$', '', 
       rm_default(
           x, 
           pattern = '"[^"]*"', 
           extract=TRUE)[[1]]
       )

    ## [1] "Salmo salar" "Hucho hucho"

**Comment by trinker** [comment]
@hwndx I incorporated your idea into `rm_between`.  Thanks for the help.
