### ISSUE TITLE
Error on email address extraction with initial capital

### ISSUE THREAD

**Issue by dswpg** [trinker/qdapRegex#30]
`qdapRegex::ex_email(c("jimmysample@sample.com", "JimmySample@sample.com"))`

> [[1]]
> [1] "jimmysample@sample.com"
> [[2]]
> [1] "ample@sample.com"

Expected behaviour in the second case is to give: JimmySample@sample.com

Installed version of qdapRegex : 0.7.2
 R version 3.5.2 (2018-12-20)
on Windows 10, 64 bit

**Comment by trinker** [comment]
Thsank you for the report.  This has been fixed in `Version: 0.7.4`
